name: MSVC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "miniconda*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_SYSREQUIRES_SUDO: 1
jobs:
  conan-with-msvc:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        compiler_version: [17]
        compiler_toolset: [v143]

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip requests
          pip3 install --upgrade conan
      - name: Configure Conan
        run: |
          conan remote add sintef ${env:CONAN_UPLOAD} --insert 0
      - name: Conan create
        run: |
          conan export . sintef/testing
      - name: Conan upload
        run: |
          conan upload -c -r sintef ${env:SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
